### ISSUE TITLE
Speech Lab - SSN Links

### ISSUE THREAD

**Issue by johananj** [ashwanthkumar/chrome-tts-tamizh#2]
Links to speech lab have changed. The home page is now http://www.ssn.edu.in/Speech_Lab/

**Comment by ashwanthkumar** [comment]
Would you be kind enough to send me a PR for the same? Thanks in advance.

**Comment by johananj** [comment]
Sorry for this response after SEVEN years! I sent you a PR. Thank you.

**Comment by ashwanthkumar** [comment]
Fixed by #4
