### ISSUE TITLE
More details needed to enhance.

### ISSUE THREAD

**Issue by satishAarbor** [ashwanthkumar/chrome-tts-tamizh#3]
hello Mr.Ashwanthkumar this is a wonderful Tamil TTS project. I'm developing a chatbot in python that can handle many language importantly tamil also i had trained my chatbot for tamil language but i need Tamil TTS method when i searched for Tamil TTS i found your project which is best among others can you provide more details to enhance your tamil TTS chrome extension project to speak my chatbot in tamil. I'm developing the TTS in javascript on Django framework.

**Comment by ashwanthkumar** [comment]
@satishAarbor What kind of details are you looking for?

**Comment by satishAarbor** [comment]
below code is my sample of javascript code.
``` io.on('bot_uttered', function(data){  
           var botMsg = data['text']
            responsiveVoice.speak(botMsg);
         $("#textArea").append("<strong>Weatherbot</strong>"+": "+botMsg+"<br>");
```

botMsg is a variable that contain message from bot and   responsiveVoice.speak(botMsg); this is used to english text to speech method here if it contain tamil language i want to say my bot in tamil language as your project done when selecting the tamil text and say it tamil in chrome as extension.

**Comment by ashwanthkumar** [comment]
So if I understand correctly, there are 2 things that're needed for what you want. 

1. Detecting if the language you want to speak is tamil or not. This is beyond the scope of this project. I can't help with that. 
2. How to make it speak Tamil text. This project when it was built, uses an API from one of the Tamil TTS engines. You can use the same to do your Tamil TTS.

**Comment by ashwanthkumar** [comment]
Since what you're trying to do is beyond the scope of this project, I'm closing this issue.

**Comment by satishAarbor** [comment]
can you tell me any open source tamil TTS API?

**Comment by ashwanthkumar** [comment]
@satishAarbor I found about this recently on ILUGC community https://github.com/fossbalaji/tamil-tts-web/. This might be of some help.
